{
  "apiVersion": 1,
  "datasources": [
    {
      "access": "proxy",
      "editable": false,
      "name": "Internal-prometheus",
      "orgId": 1,
      "type": "prometheus",
      "url": "http://prometheus-k8s.monitoring.svc:9090",
      "version": 1
    },
  ]
}