resources:
  - github.com/prometheus-operator/kube-prometheus?ref=v0.8.0

  - grafana/ingress.yaml
  - grafana/postgres.yaml
  - grafana/postgres-service.yaml

patches:
  - target:
      kind: Prometheus
      name: k8s
    path: prometheus/patch_prometheus_storage.yaml
  - target:
      kind: Prometheus
      name: k8s
    path: prometheus/patch_prometheus_retention.yaml
  - target:
      kind: Alertmanager
      name: main
    path: prometheus/patch_alertmanager_config_selector.yaml
  - target:
      kind: Deployment
      name: grafana
    path: grafana/patch_grafana_config.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - type: Opaque
    behavior: replace
    name: grafana-datasources
    namespace: monitoring
    files:
      - grafana/config/datasources.yaml
